"""Add relationship User

Revision ID: 895fdc51df30
Revises: bb092b516dc5
Create Date: 2021-12-11 03:29:44.122542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895fdc51df30'
down_revision = 'bb092b516dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
