"""Add telegram id

Revision ID: bb092b516dc5
Revises: ea34b4e51d34
Create Date: 2021-12-11 01:45:54.084023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb092b516dc5'
down_revision = 'ea34b4e51d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###
